# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import holamundo_pb2 as holamundo__pb2


class SaludadorStub(object):
    """The service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DiHola = channel.unary_unary(
                '/holamundo.Saludador/DiHola',
                request_serializer=holamundo__pb2.HelloRequest.SerializeToString,
                response_deserializer=holamundo__pb2.HelloReply.FromString,
                )


class SaludadorServicer(object):
    """The service definition.
    """

    def DiHola(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SaludadorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DiHola': grpc.unary_unary_rpc_method_handler(
                    servicer.DiHola,
                    request_deserializer=holamundo__pb2.HelloRequest.FromString,
                    response_serializer=holamundo__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'holamundo.Saludador', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Saludador(object):
    """The service definition.
    """

    @staticmethod
    def DiHola(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/holamundo.Saludador/DiHola',
            holamundo__pb2.HelloRequest.SerializeToString,
            holamundo__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
